# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LoveLifeLoveSelf/xlspec.git'

platform :ios, '7.0'
target 'UI堆栈架构' do
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'BundleImageCache','~> 2.0.6'
end
